SELECT ID, COUNT(*) AS NUM
FROM (
    SELECT REQUESTER_ID AS ID
    FROM RequestAccepted

    UNION ALL

    SELECT ACCEPTER_ID AS ID
    FROM RequestAccepted
) T
GROUP BY ID
ORDER BY NUM DESC
LIMIT 1;