SELECT CAR_ID,CASE WHEN 
MAX(CASE WHEN '2022-10-16' BETWEEN DATE(START_DATE) AND DATE(END_DATE) THEN 1
ELSE 0 END) = 1 THEN '대여중' ELSE '대여 가능' END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
ORDER BY 1 DESC