SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(O.AMOUNT*P.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY 1,2
ORDER BY 3 DESC,1

