SELECT A.PRODUCT_ID,
       CASE 
           WHEN B.NEW_PRICE IS NULL THEN 10
           ELSE B.NEW_PRICE
       END AS PRICE
FROM (SELECT DISTINCT PRODUCT_ID FROM PRODUCTS) A
LEFT JOIN (
    SELECT P.PRODUCT_ID,
           P.NEW_PRICE
    FROM PRODUCTS P
    JOIN (
        SELECT PRODUCT_ID,
               MAX(CHANGE_DATE) AS RECENT_DATE
        FROM PRODUCTS
        WHERE CHANGE_DATE <= '2019-08-16'
        GROUP BY PRODUCT_ID
    ) X
    ON P.PRODUCT_ID = X.PRODUCT_ID
    AND P.CHANGE_DATE = X.RECENT_DATE
) B
ON A.PRODUCT_ID = B.PRODUCT_ID;