SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자','국','김치','식용유')
  AND PRICE = (
      SELECT MAX(PRICE)
      FROM FOOD_PRODUCT B
      WHERE B.CATEGORY = FOOD_PRODUCT.CATEGORY
  )
ORDER BY PRICE DESC;